# Generated by Django 4.2.7 on 2023-12-08 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('VANS', 'VANS'), ('NIKE', 'NIKE'), ('ADIDAS', 'ADIDAS'), ('PUMA', 'PUMA'), ('REEBOK', 'REEBOK'), ('CONVERSE', 'CONVERSE'), ('NEW BALANCE', 'NEW BALANCE'), ('ASICS', 'ASICS'), ('UNDER ARMOUR', 'UNDER ARMOUR'), ('TIMBERLAND', 'TIMBERLAND'), ('SALOMON', 'SALOMON')], default='OTHER', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SNEAKERS', 'SNEAKERS'), ('BOOTS', 'BOOTS'), ('SANDALS', 'SANDALS'), ('SLIPPERS', 'SLIPPERS'), ('OTHER', 'OTHER')], default='OTHER', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX')], default='UNISEX', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(default='', upload_to='shoes')),
                ('sizes', models.CharField(default=0, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(default=0, max_length=100)),
                ('description', models.CharField(default=0, max_length=500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.category')),
                ('gender', models.ForeignKey(default='UNISEX', on_delete=django.db.models.deletion.DO_NOTHING, to='store.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shoe')),
            ],
        ),
    ]
