# Generated by Django 4.2.7 on 2024-01-15 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('VANS', 'VANS'), ('NIKE', 'NIKE'), ('ADIDAS', 'ADIDAS'), ('PUMA', 'PUMA'), ('REEBOK', 'REEBOK'), ('CONVERSE', 'CONVERSE'), ('NEW BALANCE', 'NEW BALANCE'), ('ASICS', 'ASICS'), ('UNDER ARMOUR', 'UNDER ARMOUR'), ('TIMBERLAND', 'TIMBERLAND'), ('SALOMON', 'SALOMON')], default='OTHER', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SNEAKERS', 'SNEAKERS'), ('BOOTS', 'BOOTS'), ('SANDALS', 'SANDALS'), ('SLIPPERS', 'SLIPPERS'), ('OTHER', 'OTHER')], default='OTHER', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX')], default='UNISEX', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], default='CASH', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_company', models.CharField(choices=[('FAN_COURIER', 'FAN_COURIER'), ('CARGUS', 'CARGUS'), ('DHL', 'DHL'), ('GLS', 'GLS'), ('SELF_PICKUP', 'SELF_PICKUP')], default='FAN_COURIER', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(default='', upload_to='shoes')),
                ('sizes', models.CharField(default=0, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('colors', models.CharField(default=0, max_length=500)),
                ('description', models.CharField(default=0, max_length=500)),
                ('sale', models.BooleanField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.category')),
                ('gender', models.ForeignKey(default='UNISEX', on_delete=django.db.models.deletion.DO_NOTHING, to='store.gender')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shoe')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.shipmentcompany'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.shoe')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
