# Generated by Django 4.2.7 on 2023-12-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='color',
        ),
        migrations.AddField(
            model_name='shoe',
            name='colors',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
