# Generated by Django 4.2.7 on 2023-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_shoe_color_shoe_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='sale',
            field=models.BooleanField(default=0),
        ),
    ]
