# Generated by Django 4.2.7 on 2023-12-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_customer_order_user_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
