# Generated by Django 4.2.7 on 2023-12-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], default='CASH', max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_company', models.CharField(choices=[('FAN_COURIER', 'FAN_COURIER'), ('CARGUS', 'CARGUS'), ('DHL', 'DHL'), ('GLS', 'GLS'), ('SELF_PICKUP', 'SELF_PICKUP')], default='FAN_COURIER', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.shipmentcompany'),
        ),
    ]
