# Generated by Django 4.2.7 on 2023-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_payment_shipmentcompany_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shipmentcompany',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
