# Generated by Django 4.2.7 on 2023-12-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_price_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
    ]
