# Generated by Django 4.2.7 on 2024-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'customer'), (3, 'provider'), (4, 'admin')], default=1),
        ),
    ]
