# Generated by Django 4.2.7 on 2023-11-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'customer'), (2, 'guest'), (3, 'seller'), (4, 'admin')], default=4, max_length=10),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
