# Generated by Django 4.2.7 on 2023-12-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'customer'), (3, 'seller'), (4, 'admin')], default=1, max_length=10),
        ),
    ]
